name: Publish Package to PyPI

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build and publish package
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade twine
          pip install wheel
          pip install setuptools
          pip install tqdm
          pip install twine
          python setup.py sdist bdist_wheel
          python -m twine upload --repository pypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}